### ISSUE TITLE
HTML demonstration problem.

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#15]
HTML page cannot show the 'Seg Output' in X-Fork model, as shown in the following figure:

![image](https://user-images.githubusercontent.com/5948971/43222270-4aa49dd4-9015-11e8-9915-fa73e9d1a4bf.png)

**Comment by kregmi** [comment]
Uncomment line 178.

**Comment by happsky** [comment]
Thank you for your quick response.
