### ISSUE TITLE
Could you share the segmentation maps of the Dayton dataset generated by RefineNet?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#16]
Could you share the segmentation maps of the Dayton dataset generated by RefineNet?

**Comment by kregmi** [comment]
I used the the code from https://github.com/guosheng/refinenet to generate the segmentation maps.  I used RefineNet model trained using ResNet-101 on Cityscapes. I hope this helps

**Comment by happsky** [comment]
Thank you for your response! Have you done some pre-processing operations before extracting segmentation maps?

**Comment by kregmi** [comment]
I resized the images to 256x256 before extracting the segmentation maps since the original image resolution is 354x354 and used the default settings of RefineNet.

**Comment by happsky** [comment]
Thank you for your help.

**Comment by happsky** [comment]
May you provide your Matlab version and gcc version?

**Comment by happsky** [comment]
Is this file "demo_predict_mscale_cityscapes.m" you used?

**Comment by kregmi** [comment]
This is what I used:  refinenet_test_example_cityscapes.m

**Comment by kregmi** [comment]
Seems like they have changed the code. Temporarily, I have shared the segmentation maps [here](https://drive.google.com/open?id=1k-fKcg8EH-Lz8joB1OuA5h4fIyv0GC3p) for you.

**Comment by yulongleo** [comment]
could you share the segmentation maps again, i really need them

**Comment by kregmi** [comment]
Please find them [here](https://drive.google.com/open?id=1DXSSMOAUC5g8813k938v58oY-GvdSjJL).
