### ISSUE TITLE
Could you share the Crossview USA (CVUSA) to me?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#17]
Could you share the Crossview USA (CVUSA) to me?

**Comment by kregmi** [comment]
The link to the dataset page is [here ](https://github.com/kregmi/cross-view-image-synthesis#datasets).
If you require the splits, please contact the original authors.

**Comment by happsky** [comment]
Is this link https://drive.google.com/drive/folders/0BzvmHzyo_zCAX3I4VG1mWnhmcGc you used?

**Comment by kregmi** [comment]
Yes it is.

**Comment by yulongleo** [comment]
Did you have the DataSet with coordinate?

**Comment by yulongleo** [comment]
I was trying to combine it into the img-location sys

**Comment by kregmi** [comment]
@yulongleo Check if you can use this dataset: http://crcv.ucf.edu/projects/Cross-View/

**Comment by yulongleo** [comment]
It always get an error when I unpack it. I'm not sure whether the data from url is correct.
Did you use this dataset before?

**Comment by kregmi** [comment]
@yulongleo I suggest you contact the authors (tyc.cong@gmail.com, chenchen870713@gmail.com) of the paper. I haven't used the dataset.
