### ISSUE TITLE
What kind of segmentation map are you used in CVUSA dataset?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#18]
@kregmi What kind of segmentation map are you used in CVUSA dataset? The color one or the black one?
If you used the color one, can you share the code for converting the back segmentation map to the color segmentation map?
Thank you in advance.

**Comment by kregmi** [comment]
I used the color (3-channel) segmentation maps.  I read/loaded the original segmentation maps provided with the CVUSA dataset using imread function of opencv in the similar manner as we do for color images and that worked for me. Hope this helps you!
