### ISSUE TITLE
Can you share the image id you shown in the paper?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#22]

**Comment by kregmi** [comment]
Can you elaborate which images you are talking about? Which figure? All of them?

**Comment by happsky** [comment]
Can you provide all, namely, Figures 5, 6 and 7.

**Comment by kregmi** [comment]
Not sure I have all you need but this should help:
**Figure 5:** 3Jzl3r0yqwdVqN48Za6-Tw.x919.y466.a-169.jpg, CGqgAsZXAc0430FXzm0Tbw.x1565.y457.a-22.jpg, KJM_se1BWbsryTteUMtn4Q.x22.y462.a172.jpg, 0AxrRh6ZroLIx1PIL4D29w.x158.y417.a-156.jpg, 7xSVKTdDnniCg3GkYOMiQA.x446.y364.a103.jpg
**Figure 6:** Z0C4WPCZE9S_DYkXYeDCRQ.x1584.y327.a-108.jpg, nk0YG7U3Wkn5Jjp9RuNu6w.x1622.y434.a-55.jpg, It8IotIuMpMdvW1I4rFuiw.x1574.y454.a74.jpg,  gGhCRWQNNYYPwAzz8lqg2w.x498.y437.a104.jpg, nHRCbw-QPnZOzWnqN6EqUA.x1532.y472.a-32.jpg
**Figure 7:** 0019405.jpg, 0021208.jpg, 0021376.jpg, 0001332.jpg, 0002462.jpg, 0000052.jpg,  0002487.jpg

**Comment by happsky** [comment]
I only check Figure 7 and all image ids are wrong except 0001332.jpg. 
Figure 7 in your paper only has 5 images, why are you provdie 7 ids? Can you double-check it?

**Comment by happsky** [comment]
![image](https://user-images.githubusercontent.com/5948971/48235696-8288ed00-e384-11e8-8ff3-0357fdfa4418.png)

Figure 7 only has 5 samples, right?

**Comment by kregmi** [comment]
Yes, ignore the other two ids.

**Comment by happsky** [comment]
My bad, I know where I got it wrong now. Thank you very much.
