### ISSUE TITLE
how can i run the test model with CPU only, which made me got the error like this.

### ISSUE THREAD

**Issue by yulongleo** [kregmi/cross-view-image-synthesis#26]
/home/yep/torch/install/bin/luajit: /home/yep/torch/install/share/lua/5.1/torch/File.lua:343: unknown Torch class <torch.CudaTensor>

**Comment by kregmi** [comment]
You will first need to convert the pretrained models to type DoubleTensor before running the test code. Since the pretrained model is saved as CudaTensor, it is throwing this error.
