### ISSUE TITLE
Can you kindly share the code of your extension paper?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#27]
Can you kindly share the code of your extension paper "Cross-view image synthesis using geometry-guided conditional GANs"?

**Comment by kregmi** [comment]
You can basically use this code for most of the experiments of the extension paper... just transform the aerial image using homography before using as input.  
These are the corresponding points used to perform homography transformation:
    	pts_src = np.array([[600, 730],[325, 600], 1155, 655], [850, 550]])
   	pts_dst = np.array([[790, 780],[210,377], [1060, 715], [770, 250]])
After homography, you need to resize the images to 256x256.
