### ISSUE TITLE
It is hard to generate cars?

### ISSUE THREAD

**Issue by happsky** [kregmi/cross-view-image-synthesis#30]
When I am training my generator, I find everything is ok except cars, as shown in the following figures:
![image](https://user-images.githubusercontent.com/5948971/53503803-6bc2ef00-3a76-11e9-83a7-4048e9d01f22.png)
![image](https://user-images.githubusercontent.com/5948971/53503834-7b423800-3a76-11e9-93c8-ebc5d182373d.png)
![image](https://user-images.githubusercontent.com/5948971/53503860-87c69080-3a76-11e9-910a-14b20dacfdba.png)
![image](https://user-images.githubusercontent.com/5948971/53503895-9614ac80-3a76-11e9-8315-13ae4437b3a6.png)

any suggestions?

**Comment by kregmi** [comment]
@happsky Can you explain about your approach and input/output combinations. Your synthesized images look very good apart for the car. Interestingly, the model is able to generate blobs at the car regions with good shapes. Further information will be helpful to provide you any suggestions.
